### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by TrevorSpear** [Pandem-Games/BindingTower#7]
- Need sample music to check out how the setting is for the music

- Need to think of how we are going to come up with the music

- tempo of the music is also another factor that will change the game significantly

**Comment by vandomej** [comment]
I'll handle the music. That's one asset type that I've been working on since high school. And yeah tempo is a factor of music, but I don't think it will change the game significantly. We aren't making crypt of the necrodancers here after all lol. I think tempo is just one factor from a set of larger much more important factors such as sound composition, compositional style, compositional themes/motifs, I think those contribute much more to the overall feel of the game than tempo.

**Comment by TrevorSpear** [comment]
I thought you just played the piano for fun. Didn't know you were more serious with it. And I feel like tempo does change the feel of the game because you get Minecraft where the music is something that makes you feel relaxed and comforted to gather resources. Then there are scary games the music can make situations so much scarier and adds this atmosphere that makes you want to jump at basically nothing.

**Comment by TrevorSpear** [comment]
Tempo was not the completely correct terminology, what I really mean is the theme.
